services:
  api:
    container_name: sbm-core
    build: ./core
    command: sh -c "sleep 10s; python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8082:8000"
    env_file:
      - ./.env
    volumes:
      - ./core:/usr/src/app/core
      - ./franchise:/usr/src/app/franchise
      - ./catalog:/usr/src/app/catalog
      - ./accounting:/usr/src/app/accounting
      - ./support:/usr/src/app/support
      - ./price:/usr/src/app/price
      - ./config:/usr/src/app/config
      - ./fiscal:/usr/src/app/fiscal
      - ./inventory:/usr/src/app/inventory
      - ./sales:/usr/src/app/sales
      - ./users:/usr/src/app/users
      - ./templates:/usr/src/app/templates
      - ./manage.py:/usr/src/app/manage.py
      - ./.env:/usr/src/app/.env
      - /etc/localtime:/etc/localtime:ro      # <-- Añadido para zona horaria
    networks:
      - sbm-network

networks:
  sbm-network:
    external: true
