version: '3.8'

services:
  api:
    container_name: sbm-core
    build: ./core
    command: sh -c "sleep 10s; python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8083:8002"
    env_file:
      - ./.env
    volumes:
      - ./core:/usr/src/app/core
      - ./users:/usr/src/app/users
      - ./authz:/usr/src/app/authz
      - ./products:/usr/src/app/products
      - ./providers:/usr/src/app/providers
      - ./pricing:/usr/src/app/pricing
      - ./documentation:/usr/src/app/documentation
      - ./sales:/usr/src/app/sales
      - ./templates:/usr/src/app/templates
      - ./manage.py:/usr/src/app/manage.py
    networks:
      - sbm-network

networks:
  sbm-network:
    external: true
    name: sbm-db_sbm-network
