sonar.projectKey=SBM-API
sonar.projectName=SBM-API
sonar.sourceEncoding=UTF-8

sonar.sources=accounting,calculation,catalog,clients,config,core,fiscal,franchise,inventory,module,price,sales,support,users
sonar.tests=accounting,calculation,catalog,clients,config,fiscal,franchise,inventory,module,price,sales,support,users
sonar.test.inclusions=**/tests.py,**/tests/**/*.py
sonar.exclusions=**/migrations/**,**/__pycache__/**,**/tests.py,**/tests/**
sonar.coverage.exclusions=**/tests.py,**/tests/**,manage.py
sonar.python.coverage.reportPaths=coverage.xml
