"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 4.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
import environ  # type: ignore

env = environ.Env()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

environ.Env.read_env(os.path.join(BASE_DIR, ".env"))

SECRET_KEY = env("SECRET_KEY")
DEBUG = env("DEBUG")
ALLOWED_HOSTS = str(env("ALLOWED_HOSTS")).split(",") + [
    "sbm-manager",
    "sbm_manager",
    "localhost",
    "127.0.0.1",
    "sbm-core",
]

# Application definition

BASE_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

THIRD_APPS = [
    "rest_framework",
    "corsheaders",
    "django_filters",
]

OWN_APPS = [
    "franchise",  # Gestión de franquicias
    "catalog",  # Gestión de catálogo
]

INSTALLED_APPS = [
    "jazzmin",  # Django Jazzmin - tema moderno para admin
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "corsheaders",
    "django_filters",
    "franchise",  # Gestión de franquicias
    "catalog",  # Gestión de catálogo
    "accounting",  # Gestión de contabilidad
    "support",  # Soporte
    "price",  # Precios
    "config",  # Configuración
    "fiscal",  # Fiscal
    "inventory",  # Inventario
    "sales",  # Ventas
    "calculation",  # Calculos y formulas
    "module",  # Modulos
    "users",  # Usuarios
    "clients",  # Clientes
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",  # Debe ir antes de CommonMiddleware
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": env("DB_NAME"),
        "USER": env("DB_USER"),
        "PASSWORD": env("DB_PASSWORD"),
        "HOST": env("DB_HOST"),
        "PORT": env("DB_PORT"),
        "OPTIONS": {
            "options": "-c search_path=sbm_business,ditaly_pasta,analytics,public",
            "connect_timeout": 10,
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = env("LANGUAGE_CODE")

TIME_ZONE = env("TIME_ZONE")

USE_I18N = env("USE_I18N")

USE_TZ = env("USE_TZ")


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = env("STATIC_URL")

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Django REST Framework Configuration
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.BasicAuthentication",
        "users.authentication.CustomTokenAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 20,
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
        "rest_framework.renderers.BrowsableAPIRenderer",
    ],
}

# CORS Configuration
CORS_ALLOW_ALL_ORIGINS = True  # Solo para desarrollo
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS = str(env("CORS_ALLOWED_ORIGINS")).split(",") + [
    "http://localhost:8080",
    "http://localhost:8082",
    "http://sbm_manager:8080",
    "http://sbm-core:8082",
]

# === Configuración de entorno ===
DJANGO_ENV = os.environ.get("DJANGO_ENV", "development")

# === Google Auth solo en producción ===
if DJANGO_ENV == "production":
    # Ejemplo de configuración de Google Auth (ajusta según tu integración real)
    # INSTALLED_APPS += ['social_django']
    # AUTHENTICATION_BACKENDS = [
    #     'social_core.backends.google.GoogleOAuth2',
    #     # ...otros backends que uses...
    # ]
    # SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = env("GOOGLE_OAUTH2_KEY")
    # SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = env("GOOGLE_OAUTH2_SECRET")
    pass
# En desarrollo, Google Auth está desactivado

# === Configuración de usuario de prueba para desarrollo ===
MOCK_USER_UUID = os.environ.get("MOCK_USER_UUID", "mock-uuid")
MOCK_USER_EMAIL = os.environ.get("MOCK_USER_EMAIL", "mock@example.com")
MOCK_USER_NAME = os.environ.get("MOCK_USER_NAME", "MOCKUSER")
MOCK_USER_TOKEN = os.environ.get("MOCK_USER_TOKEN", "mock-token")

GOOGLE_CLIENT_ID = os.environ.get(
    "GOOGLE_CLIENT_ID",
    "815958124165-c4jtlvju3ngm68ecpgqf3k208tqd984f.apps.googleusercontent.com",
)


# Disable Django migrations for business apps - using Flyway instead
# Enable migrations only for Django system apps
MIGRATION_MODULES = {
    "franchise": None,  # Desactivar migraciones para usar Flyway
    "catalog": None,  # Desactivar migraciones para usar Flyway
    "accounting": None,  # Desactivar migraciones para usar Flyway
    "support": None,  # Desactivar migraciones para usar Flyway
    "price": None,  # Desactivar migraciones para usar Flyway
    "config": None,  # Desactivar migraciones para usar Flyway
    "fiscal": None,  # Desactivar migraciones para usar Flyway
    "inventory": None,  # Desactivar migraciones para usar Flyway
    "sales": None,  # Desactivar migraciones para usar Flyway
    "calculation": None,  # Desactivar migraciones para usar Flyway
    "module": None,  # Desactivar migraciones para usar Flyway
    "users": None,  # Desactivar migraciones para usar Flyway
    "clients": None,  # Desactivar migraciones para usar Flyway
    # Django system apps - migrations enabled
    # 'admin': None,  # Comentado para permitir migraciones
    # 'auth': None,   # Comentado para permitir migraciones
    # 'contenttypes': None,  # Comentado para permitir migraciones
    # 'sessions': None,  # Comentado para permitir migraciones
}

# Django Jazzmin Configuration
JAZZMIN_SETTINGS = {
    "site_title": "SBM-API Admin",
    "site_header": "SBM-API",
    "site_brand": "SBM-API",
    "site_logo": None,
    "welcome_sign": "Bienvenido a SBM-API",
    "copyright": "SBM-API Ltd",
    "search_model": ["auth.User"],
    "user_avatar": None,
    "topmenu_links": [
        {"name": "Home", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "API", "url": "/", "new_window": True},
    ],
    "show_sidebar": True,
    "navigation_expanded": True,
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
    },
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",
    "related_modal_active": True,
    "custom_css": None,
    "custom_js": None,
    "show_ui_builder": False,
    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {
        "auth.user": "collapsible",
        "auth.group": "vertical_tabs",
    },
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-success",
    "accent": "accent-teal",
    "navbar": "navbar-dark",
    "no_navbar_border": False,
    "navbar_fixed": False,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": False,
    "sidebar": "sidebar-dark-success",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "cosmo",
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success",
    },
}


CSRF_TRUSTED_ORIGINS = [
    "http://localhost:8080",
    "http://localhost:8082",
]
